## GENERATED BY AI

#!/usr/bin/env python3
"""
Parse repeated LSF simulation output files and plot scaling results.

Expected files:
- simulation_<jobid>.out
- simulation_parallel_<jobid>.out

This script:
- parses all matching .out files
- checks whether result tables are identical
- groups repeated runs by core count
- plots:
    1) runtime vs cores (all points + mean ± std)
    2) CPU time vs cores (all points + mean ± std)
    3) speedup vs cores (based on mean runtime)
    4) CPU-time / runtime ratio vs cores

Usage:
    python plot_parallel.py .
    python plot_parallel.py . --save scaling.png
"""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, stdev
from typing import Optional

import matplotlib.pyplot as plt


@dataclass
class RunRecord:
    path: Path
    job_id: str
    kind: str
    cores: int
    runtime_sec: Optional[float]
    cpu_time_sec: Optional[float]
    max_memory_mb: Optional[float]
    avg_memory_mb: Optional[float]
    result_header: Optional[str]
    result_rows: list[str]


@dataclass
class GroupStats:
    cores: int
    n: int
    runtime_mean: float
    runtime_std: float
    runtime_min: float
    runtime_max: float
    cpu_mean: float
    cpu_std: float
    cpu_min: float
    cpu_max: float
    cpu_runtime_ratio_mean: float
    cpu_runtime_ratio_std: float


def parse_seconds(text: str) -> Optional[float]:
    m = re.search(r"([0-9]+(?:\.[0-9]+)?)", text)
    return float(m.group(1)) if m else None


def parse_memory_mb(text: str) -> Optional[float]:
    m = re.search(r"([0-9]+(?:\.[0-9]+)?)\s*MB", text, re.IGNORECASE)
    return float(m.group(1)) if m else None


def extract_result_section(lines: list[str]) -> tuple[Optional[str], list[str]]:
    header_idx = None
    for i, line in enumerate(lines):
        if line.strip().startswith("building_id,"):
            header_idx = i
            break

    if header_idx is None:
        return None, []

    header = lines[header_idx].strip()
    rows: list[str] = []

    for line in lines[header_idx + 1:]:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("----"):
            break
        if re.match(r"^\d+\s*,", stripped):
            rows.append(stripped)

    return header, rows


def parse_out_file(path: Path) -> RunRecord:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()

    job_match = re.search(r"(\d+)\.out$", path.name)
    job_id = job_match.group(1) if job_match else "unknown"

    kind = "parallel" if "simulation_parallel2_" in path.name else "baseline"

    cores = 1
    cores_match = re.search(r"^\s*cores:\s*(\d+)\s*$", text, re.MULTILINE)
    if cores_match:
        cores = int(cores_match.group(1))

    runtime_match = re.search(r"Run time\s*:\s*(.+)", text)
    cpu_time_match = re.search(r"CPU time\s*:\s*(.+)", text)
    max_memory_match = re.search(r"Max Memory\s*:\s*(.+)", text)
    avg_memory_match = re.search(r"Average Memory\s*:\s*(.+)", text)

    runtime_sec = parse_seconds(runtime_match.group(1)) if runtime_match else None
    cpu_time_sec = parse_seconds(cpu_time_match.group(1)) if cpu_time_match else None
    max_memory_mb = parse_memory_mb(max_memory_match.group(1)) if max_memory_match else None
    avg_memory_mb = parse_memory_mb(avg_memory_match.group(1)) if avg_memory_match else None

    header, rows = extract_result_section(lines)

    return RunRecord(
        path=path,
        job_id=job_id,
        kind=kind,
        cores=cores,
        runtime_sec=runtime_sec,
        cpu_time_sec=cpu_time_sec,
        max_memory_mb=max_memory_mb,
        avg_memory_mb=avg_memory_mb,
        result_header=header,
        result_rows=rows,
    )


def discover_runs(directory: Path) -> list[RunRecord]:
    files = list(directory.glob("simulation_parallel2*.out"))
    files += list((directory / "../base").resolve().glob("simulation*.out"))

    runs = [parse_out_file(f) for f in files]
    runs = [r for r in runs if r.runtime_sec is not None]

    if not runs:
        raise FileNotFoundError(f"No parseable simulation*.out files found in {directory}")

    return runs


def compare_results(runs: list[RunRecord]) -> tuple[bool, str]:
    reference = None
    reference_name = None

    for run in runs:
        if run.result_header and run.result_rows:
            reference = (run.result_header, run.result_rows)
            reference_name = run.path.name
            break

    if reference is None:
        return False, "No simulation result table found in any file."

    ref_header, ref_rows = reference

    for run in runs:
        if run.result_header != ref_header:
            return False, f"Header mismatch in {run.path.name} (reference: {reference_name})."
        if run.result_rows != ref_rows:
            return False, f"Data row mismatch in {run.path.name} (reference: {reference_name})."

    return True, f"All runs produced identical result tables ({len(ref_rows)} rows)."


def build_group_stats(runs: list[RunRecord]) -> list[GroupStats]:
    grouped: dict[int, list[RunRecord]] = defaultdict(list)
    for run in runs:
        grouped[run.cores].append(run)

    stats: list[GroupStats] = []
    for cores in sorted(grouped):
        group = grouped[cores]

        runtimes = [r.runtime_sec for r in group if r.runtime_sec is not None]
        cpu_times = [r.cpu_time_sec for r in group if r.cpu_time_sec is not None]
        ratios = [
            r.cpu_time_sec / r.runtime_sec
            for r in group
            if r.cpu_time_sec is not None and r.runtime_sec is not None and r.runtime_sec > 0
        ]

        if not runtimes:
            continue

        runtime_mean = mean(runtimes)
        runtime_std = stdev(runtimes) if len(runtimes) >= 2 else 0.0
        runtime_min = min(runtimes)
        runtime_max = max(runtimes)

        cpu_mean = mean(cpu_times) if cpu_times else float("nan")
        cpu_std = stdev(cpu_times) if len(cpu_times) >= 2 else 0.0
        cpu_min = min(cpu_times) if cpu_times else float("nan")
        cpu_max = max(cpu_times) if cpu_times else float("nan")

        ratio_mean = mean(ratios) if ratios else float("nan")
        ratio_std = stdev(ratios) if len(ratios) >= 2 else 0.0

        stats.append(
            GroupStats(
                cores=cores,
                n=len(runtimes),
                runtime_mean=runtime_mean,
                runtime_std=runtime_std,
                runtime_min=runtime_min,
                runtime_max=runtime_max,
                cpu_mean=cpu_mean,
                cpu_std=cpu_std,
                cpu_min=cpu_min,
                cpu_max=cpu_max,
                cpu_runtime_ratio_mean=ratio_mean,
                cpu_runtime_ratio_std=ratio_std,
            )
        )

    return stats


def print_summary(stats: list[GroupStats]) -> None:
    baseline = next((s for s in stats if s.cores == 1), None)

    t1_mean = baseline.runtime_mean if baseline else 0

    print("\nGrouped summary:")
    print("-" * 140)
    print(
        f"{'cores':>5} {'n':>4} {'mean_rt(s)':>12} {'std_rt':>10} "
        f"{'mean_cpu(s)':>12} {'std_cpu':>10} {'cpu/rt':>10} "
        f"{'mean_speedup':>14} {'eff(mean)':>11}"
    )
    print("-" * 140)

    for s in stats:
        mean_speedup = t1_mean / s.runtime_mean
        eff = mean_speedup / s.cores
        print(
            f"{s.cores:5d} {s.n:4d} {s.runtime_mean:12.2f} {s.runtime_std:10.2f} "
            f"{s.cpu_mean:12.2f} {s.cpu_std:10.2f} {s.cpu_runtime_ratio_mean:10.3f} "
            f"{mean_speedup:14.3f} {eff:11.3f}"
        )

    print("-" * 140)
    print(f"Mean baseline runtime (1 core): {t1_mean:.2f} s\n")


def make_plots(
    runs: list[RunRecord],
    stats: list[GroupStats],
    save_path: Optional[sPath] = None,
) -> None:
    baseline = next((s for s in stats if s.cores == 1), None)
    if baseline is None:
        raise ValueError("No baseline (1-core) runs found.")

    t1_mean = baseline.runtime_mean

    cores = [s.cores for s in stats]
    runtime_means = [s.runtime_mean for s in stats]
    runtime_stds = [s.runtime_std for s in stats]
    cpu_means = [s.cpu_mean for s in stats]
    cpu_stds = [s.cpu_std for s in stats]

    mean_speedups = [t1_mean / s.runtime_mean for s in stats]
    ideal_speedup = cores

    fig = plt.figure(figsize=(13, 9))
    gs = fig.add_gridspec(2, 2, height_ratios=[1, 1])

    ax1 = fig.add_subplot(gs[0, 0])
    ax2 = fig.add_subplot(gs[0, 1])
    ax3 = fig.add_subplot(gs[1, :])

    def style_axis(ax):
        ax.grid(True, alpha=0.3)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.set_xlabel("Worker processes")

    # Runtime vs cores
    for core in sorted({r.cores for r in runs}):
        ys = [
            r.runtime_sec
            for r in runs
            if r.cores == core and r.runtime_sec is not None
        ]
        xs = [core] * len(ys)
        ax1.scatter(xs, ys, alpha=0.5, s=28)

    ax1.errorbar(
        cores,
        runtime_means,
        yerr=runtime_stds,
        fmt="-o",
        capsize=4,
        linewidth=2,
        markersize=6,
        label="Mean ± std",
    )
    ax1.set_title("Wallclock Runtime")
    ax1.set_ylabel("Runtime (s)")
    style_axis(ax1)
    ax1.legend(frameon=False)

    # CPU time vs cores
    for core in sorted({r.cores for r in runs}):
        ys = [
            r.cpu_time_sec
            for r in runs
            if r.cores == core and r.cpu_time_sec is not None
        ]
        xs = [core] * len(ys)
        ax2.scatter(xs, ys, alpha=0.5, s=28)

    ax2.errorbar(
        cores,
        cpu_means,
        yerr=cpu_stds,
        fmt="-o",
        capsize=4,
        linewidth=2,
        markersize=6,
        label="Mean ± std",
    )
    ax2.set_title("CPU Time")
    ax2.set_ylabel("CPU time (s)")
    style_axis(ax2)
    ax2.legend(frameon=False)

    # Speedup vs cores
    ax3.plot(
        cores,
        mean_speedups,
        marker="o",
        linewidth=2.5,
        markersize=6,
        label="Measured",
    )
    ax3.plot(
        cores,
        ideal_speedup,
        linestyle="--",
        linewidth=2,
        label="Ideal linear speedup",
    )
    ax3.set_title("Speedup")
    ax3.set_ylabel("Speedup")
    style_axis(ax3)
    ax3.legend(frameon=False)

    fig.tight_layout()

    if save_path:
        fig.savefig(save_path, dpi=200, bbox_inches="tight")
        print(f"Saved figure to: {save_path}")

    plt.show()

def main() -> None:
    parser = argparse.ArgumentParser(description="Parse repeated simulation output files and plot scaling.")
    parser.add_argument(
        "directory",
        nargs="?",
        default=".",
        help="Directory containing simulation*.out files (default: current directory)",
    )
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Optional voutput image path, e.g. scaling.png",
    )
    args = parser.parse_args()

    runs = discover_runs(Path(args.directory))

    ok, message = compare_results(runs)
    print(message)

    stats = build_group_stats(runs)
    print_summary(stats)
    make_plots(runs, stats, save_path=args.save)


if __name__ == "__main__":
    main()
