## GENERATED BY AI

#!/usr/bin/env python3
from pathlib import Path
import re
import statistics
import matplotlib.pyplot as plt


BASE_DIR = Path("base")
STATIC_DIR = Path("static_scheduling")
DYNAMIC_DIR = Path("dynamic_scheduling")

SERIAL_PATTERN = "simulation_*.out"
PARALLEL_PATTERN = "simulation_parallel2_*.out"


def parse_runtime_and_cores(path: Path):
    text = path.read_text(errors="ignore")

    runtime_match = re.search(r"Run time\s*:\s*([0-9.]+)\s*sec\.", text)
    if not runtime_match:
        return None

    cores_match = re.search(r"^cores:\s*(\d+)", text, re.MULTILINE)

    runtime = float(runtime_match.group(1))
    cores = int(cores_match.group(1)) if cores_match else None
    return cores, runtime


def collect_parallel_results(folder: Path):
    raw_data = {}

    for path in sorted(folder.glob(PARALLEL_PATTERN)):
        parsed = parse_runtime_and_cores(path)
        if parsed is None:
            print(f"Skipping {path} (could not parse runtime)")
            continue

        cores, runtime = parsed
        if cores is None:
            print(f"Skipping {path} (missing cores line)")
            continue

        raw_data.setdefault(cores, []).append(runtime)

    mean_data = {}
    std_data = {}

    for cores, runtimes in sorted(raw_data.items()):
        mean_data[cores] = statistics.mean(runtimes)
        std_data[cores] = statistics.stdev(runtimes) if len(runtimes) > 1 else 0.0

    return raw_data, mean_data, std_data


def collect_serial_baseline(folder: Path):
    runtimes = []

    for path in sorted(folder.glob(SERIAL_PATTERN)):
        parsed = parse_runtime_and_cores(path)
        if parsed is None:
            print(f"Skipping {path} (could not parse runtime)")
            continue

        _, runtime = parsed
        runtimes.append(runtime)

    if not runtimes:
        return [], None, 0.0

    mean_runtime = statistics.mean(runtimes)
    std_runtime = statistics.stdev(runtimes) if len(runtimes) > 1 else 0.0
    return runtimes, mean_runtime, std_runtime


def compute_speedup(parallel_mean_data, serial_baseline):
    if serial_baseline is None:
        return {}

    return {
        cores: serial_baseline / runtime
        for cores, runtime in parallel_mean_data.items()
    }


def make_combined_plot(
    serial_mean,
    static_mean, static_std, static_speedup,
    dynamic_mean, dynamic_std, dynamic_speedup,
    output_path="scheduling_comparison.png"
):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # ----- Left plot: Runtime -----
    ax = axes[0]

    if serial_mean is not None:
        ax.axhline(serial_mean, linestyle="--", label="Serial baseline")

    if static_mean:
        x = sorted(static_mean.keys())
        y = [static_mean[c] for c in x]
        yerr = [static_std[c] for c in x]
        ax.errorbar(
            x, y, yerr=yerr, marker="s", capsize=4,
            label="Static scheduling"
        )

    if dynamic_mean:
        x = sorted(dynamic_mean.keys())
        y = [dynamic_mean[c] for c in x]
        yerr = [dynamic_std[c] for c in x]
        ax.errorbar(
            x, y, yerr=yerr, marker="o", capsize=4,
            label="Dynamic scheduling"
        )

    ax.set_xlabel("Number of cores")
    ax.set_ylabel("Run time (seconds)")
    ax.set_title("Runtime comparison")
    ax.grid(True, alpha=0.3)
    ax.legend()

    # ----- Right plot: Speedup -----
    ax = axes[1]
    max_core = 0

    if static_speedup:
        x = sorted(static_speedup.keys())
        y = [static_speedup[c] for c in x]
        ax.plot(x, y, marker="s", label="Static scheduling")
        max_core = max(max_core, max(x))

    if dynamic_speedup:
        x = sorted(dynamic_speedup.keys())
        y = [dynamic_speedup[c] for c in x]
        ax.plot(x, y, marker="o", label="Dynamic scheduling")
        max_core = max(max_core, max(x))

    if max_core > 0:
        ideal_x = list(range(1, max_core + 1))
        ideal_y = ideal_x
        ax.plot(ideal_x, ideal_y, linestyle="--", label="Ideal linear speedup")

    ax.set_xlabel("Number of cores")
    ax.set_ylabel("Speedup")
    ax.set_title("Speedup comparison")
    ax.grid(True, alpha=0.3)
    ax.legend()

    plt.tight_layout()
    plt.savefig(output_path, dpi=200)
    plt.close()


def print_parallel_summary(name, raw_data, mean_data, speedup):
    print(f"\n=== {name} ===")
    if not mean_data:
        print("No valid parallel log files found.")
        return

    for cores in sorted(mean_data):
        n = len(raw_data[cores])
        print(
            f"{cores:>3} cores | runs={n:>2} | "
            f"mean runtime={mean_data[cores]:>8.2f} s | "
            f"speedup={speedup.get(cores, float('nan')):>6.2f}"
        )


def main():
    serial_runtimes, serial_mean, serial_std = collect_serial_baseline(BASE_DIR)

    static_raw, static_mean, static_std = collect_parallel_results(STATIC_DIR)
    dynamic_raw, dynamic_mean, dynamic_std = collect_parallel_results(DYNAMIC_DIR)

    static_speedup = compute_speedup(static_mean, serial_mean)
    dynamic_speedup = compute_speedup(dynamic_mean, serial_mean)

    print("=== Serial baseline ===")
    if serial_mean is None:
        print(f"No valid serial baseline logs found in {BASE_DIR}.")
    else:
        print(f"Runs: {len(serial_runtimes)}")
        print(f"Mean runtime: {serial_mean:.2f} s")
        print(f"Std runtime:  {serial_std:.2f} s")

    print_parallel_summary(
        "Static scheduling",
        static_raw,
        static_mean,
        static_speedup
    )

    print_parallel_summary(
        "Dynamic scheduling",
        dynamic_raw,
        dynamic_mean,
        dynamic_speedup
    )

    make_combined_plot(
        serial_mean,
        static_mean, static_std, static_speedup,
        dynamic_mean, dynamic_std, dynamic_speedup,
        output_path="scheduling_comparison.png"
    )

    print("\nSaved:")
    print("  scheduling_comparison.png")


if __name__ == "__main__":
    main()
